### ISSUE TITLE
移动端适配利器-rem的设置

### ISSUE THREAD

**Issue by metroluffy** [metroluffy/blog#24]
> 题记：之前项目迭代时遇到一张纯html页面在移动端的实现，涉及到一部分元素大小、定位等问题，rem的设置算是很简单的一部分，这里也是引用了很多前辈文章的片段，算是整理，方便以后索引参考。
>  从语雀同步（2019.6.27）

先看下em这个单位，1em与当前元素的字体大小相同（更具体地说，一个大写字母M的宽度）。
CSS样式被应用之前，浏览器给网页设置的默认基础字体大小是16像素，这意味着对一个元素来说1em的计算值默认为16像素。
但是要小心—em单位是会继承父元素的字体大小，所以如果在父元素上设置了不同的字体大小，em的像素值就会变得复杂。
现在不要过于担心这个问题，我们将在后面的文章和模块中更详细地介绍继承和字体大小设置。em是Web开发中最常用的相对单位。
rem和em以同样的方式工作，但它总是等于默认基础字体大小的尺寸；继承的字体大小将不起作用，所以这听起来像一个比em更好的选择，虽然在旧版本的IE上不被支持。
本文考虑的是移动端，目前在Ios：6.1系统以上及Android：2.1系统以上都支持，因此基本兼容性是没啥问题。
主要是root font-size设置方面，有两种方法，一个是通过js设置，一个是通过css mediaQuery设置。
### JS方案：
这是一份跑在目前H5的代码，以50px为1rem（设计稿375px标准），在页面布局发送变化（resize或屏幕方向变化）自适应。
```javascript
var htmlDom = document.documentElement;
var windowWidth = htmlDom.clientWidth;
var evt = 'onorientationchange' in window ? 'orientationchange' : 'resize';
var tid;
htmlDom.style.fontSize = windowWidth / 7.5 + 'px';
(function () {
  document.addEventListener('DOMContentLoaded', function () {
    if (!htmlDom.style.fontSize) {
      var htmlDomProtect = document.documentElement;
      var windowWidth = htmlDomProtect.clientWidth;
      htmlDomProtect.style.fontSize = windowWidth / 7.5 + 'px';
    }
  }, false);
})();
window.addEventListener(evt, function () {
  clearTimeout(tid); // 避免执行两次
  tid = setTimeout(function () {
    var htmlDomProtect = document.documentElement;
    var windowWidth = htmlDomProtect.clientWidth;
    htmlDomProtect.style.fontSize = windowWidth / 7.5 + 'px';
  }, 200);
}, false);
```
使用JS来获取屏幕宽度的好处在于可以100%适配所有的机型宽度，因为其<html>元素的基准尺寸是直接算出来的。
既然是JS代码，为了避免造成因为动态设置<html>元素的font-size而造成页面抖动，一般这部分代码我们放在header底部去加载或者在页面内容加载完成执行（如上）。
上述的代码，有些问题，比如img元素如父元素不设置FontSize会默认继承body的font-size，而body继承至html，
这样如果是图片丢失显示出alt文字，就会有问题，算是一个小细节，解决办法，一个是手动指定一下img的font-size，一个是如下面的CSS3方案，设置一下body大小（推荐）。
在实现上有兼容性更好的更详细优化的方案，参见[Rem自适应js-优化flexible.js](http://caibaojian.com/simple-flexible.html)

代码摘录如下：

```javascript

//designWidth:设计稿的实际宽度值，需要根据实际设置
//maxWidth:制作稿的最大宽度值，需要根据实际设置
//这段js的最后面有两个参数记得要设置，一个为设计稿实际宽度，一个为制作稿最大宽度，例如设计稿为750，最大宽度为750，则为(750,750)
;(function(designWidth, maxWidth) {
	var doc = document,
	win = window,
	docEl = doc.documentElement,
	remStyle = document.createElement("style"),
	tid;

	function refreshRem() {
		var width = docEl.getBoundingClientRect().width;
		maxWidth = maxWidth || 540;
		width>maxWidth && (width=maxWidth);
		var rem = width * 100 / designWidth;
		remStyle.innerHTML = 'html{font-size:' + rem + 'px;}';
	}

	if (docEl.firstElementChild) {
		docEl.firstElementChild.appendChild(remStyle);
	} else {
		var wrap = doc.createElement("div");
		wrap.appendChild(remStyle);
		doc.write(wrap.innerHTML);
		wrap = null;
	}
	//要等 viewport 设置好后才能执行 refreshRem，不然 refreshRem 会执行2次；
	refreshRem();

	win.addEventListener("resize", function() {
		clearTimeout(tid); //防止执行两次
		tid = setTimeout(refreshRem, 300);
	}, false);

	win.addEventListener("pageshow", function(e) {
		if (e.persisted) { // 浏览器后退的时候重新计算
			clearTimeout(tid);
			tid = setTimeout(refreshRem, 300);
		}
	}, false);

	if (doc.readyState === "complete") {
		doc.body.style.fontSize = "16px";
	} else {
		doc.addEventListener("DOMContentLoaded", function(e) {
			doc.body.style.fontSize = "16px";
		}, false);
	}
})(750, 750);
```
### CSS3方案：
既然只是为了根据屏幕宽度来设置<html>元素的字体大小，CSS3的媒体查询也可以做到，如苏宁，代码如下：
```css
        html {
            font-size: 50px
        }

        body {
            font-size: 24px
        }

        @media screen and (min-width:320px) {
            html {
                font-size: 21.33px
            }

            body {
                font-size: 12px
            }
        }

        @media screen and (min-width:360px) {
            html {
                font-size: 24px
            }

            body {
                font-size: 12px
            }
        }

        @media screen and (min-width:375px) {
            html {
                font-size: 25px
            }

            body {
                font-size: 12px
            }
        }

        @media screen and (min-width:384px) {
            html {
                font-size: 25.6px
            }

            body {
                font-size: 14px
            }
        }

        @media screen and (min-width:400px) {
            html {
                font-size: 26.67px
            }

            body {
                font-size: 14px
            }
        }

        @media screen and (min-width:414px) {
            html {
                font-size: 27.6px
            }

            body {
                font-size: 14px
            }
        }

        @media screen and (min-width:424px) {
            html {
                font-size: 28.27px
            }

            body {
                font-size: 14px
            }
        }

        @media screen and (min-width:480px) {
            html {
                font-size: 32px
            }

            body {
                font-size: 15.36px
            }
        }

        @media screen and (min-width:540px) {
            html {
                font-size: 36px
            }

            body {
                font-size: 17.28px
            }
        }

        @media screen and (min-width:720px) {
            html {
                font-size: 48px
            }

            body {
                font-size: 23.04px
            }
        }

        @media screen and (min-width:750px) {
            html {
                font-size: 50px
            }

            body {
                font-size: 24px
            }
        }
```
还是比较详细的，用的时候只要根据设计稿给的大小换算一下。相当于js来说，缺点是需根据设计稿来算rem，而且还是写死的，
如存在未考虑的设备宽度或者将来有了新的，需要更新代码，届时会很麻烦。
rem作为一种简单粗暴解决不同屏幕下视图的区别的一种方案，它可以解决本文出现的问题以及绝大多数移动端适配屏幕尺寸的问题。
但是既然它并不是一个完美的解决方案，那就有其局限性所在。
比如在文字显示方面，

> iOS与Android平台的适配方式背后隐藏的设计哲学是这样的：阅读文字时，可读性较好的文字字号行距等绝对尺寸数值组合与文字所在媒介的绝对尺寸关系不大。（可以这样简单理解：A4大小的报纸和A3大小甚至更大的报纸，舒适的阅读字号绝对尺寸是一样的，因为他们都需要拿在手里阅读，在手机也是上同理）；在看图片视频时，图片、视频的比例应该是固定的，不应该出现拉伸变形的情况。而rem用在字号时，使字号在不同屏幕上的绝对尺寸不一致，违背了设计哲学。

更多的可以看下下面的参考文档。
### 参考文档：
1、[简单粗暴的移动端适配方案 - REM](https://imweb.io/topic/5a523cc0a192c3b460fce3a5)
2、[rem不是神农草，治不了移动端百病](http://imweb.io/topic/5745adf5a94f742c1db63485)
### 拓展阅读：
1、[利用视口单位实现适配布局](https://aotu.io/notes/2017/04/28/2017-4-28-CSS-viewport-units/index.html)
